window.esdocSearchIndex = [
  [
    "tariff-psroo/tariff-psroo/src/index.js~psr",
    "class/tariff-psroo/src/index.js~PSR.html",
    "<span>PSR</span> <span class=\"search-result-import-path\">tariff-psroo/tariff-psroo/src/index.js</span>",
    "class"
  ],
  [
    "tariff-psroo/tariff-psroo/src/template.js~template",
    "function/index.html#static-function-template",
    "<span>template</span> <span class=\"search-result-import-path\">tariff-psroo/tariff-psroo/src/template.js</span>",
    "function"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "tariff-psroo/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "tariff-psroo/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "tariff-psroo/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "tariff-psroo/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "tariff-psroo/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "tariff-psroo/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "tariff-psroo/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "tariff-psroo/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "tariff-psroo/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "tariff-psroo/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "tariff-psroo/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "tariff-psroo/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "tariff-psroo/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "tariff-psroo/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "tariff-psroo/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "tariff-psroo/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "tariff-psroo/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "tariff-psroo/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "tariff-psroo/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "tariff-psroo/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "tariff-psroo/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "tariff-psroo/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "tariff-psroo/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "tariff-psroo/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "tariff-psroo/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "tariff-psroo/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "tariff-psroo/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "tariff-psroo/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "tariff-psroo/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "tariff-psroo/.external-ecmascript.js~String",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "tariff-psroo/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "tariff-psroo/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "tariff-psroo/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "tariff-psroo/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "tariff-psroo/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "tariff-psroo/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "tariff-psroo/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "tariff-psroo/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "tariff-psroo/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "tariff-psroo/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "tariff-psroo/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "tariff-psroo/.external-ecmascript.js~function",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "tariff-psroo/.external-ecmascript.js~null",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "tariff-psroo/.external-ecmascript.js~number",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "tariff-psroo/.external-ecmascript.js~object",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "tariff-psroo/.external-ecmascript.js~string",
    "external"
  ],
  [
    "tariff-psroo/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "tariff-psroo/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "tariff-psroo/src/grammar.js",
    "file/tariff-psroo/src/grammar.js.html",
    "tariff-psroo/src/grammar.js",
    "file"
  ],
  [
    "tariff-psroo/src/index.js",
    "file/tariff-psroo/src/index.js.html",
    "tariff-psroo/src/index.js",
    "file"
  ],
  [
    "tariff-psroo/src/index.js~psr#categories",
    "class/tariff-psroo/src/index.js~PSR.html#instance-member-categories",
    "tariff-psroo/src/index.js~PSR#categories",
    "member"
  ],
  [
    "tariff-psroo/src/index.js~psr#constructor",
    "class/tariff-psroo/src/index.js~PSR.html#instance-constructor-constructor",
    "tariff-psroo/src/index.js~PSR#constructor",
    "method"
  ],
  [
    "tariff-psroo/src/index.js~psr#dump",
    "class/tariff-psroo/src/index.js~PSR.html#instance-method-dump",
    "tariff-psroo/src/index.js~PSR#dump",
    "method"
  ],
  [
    "tariff-psroo/src/index.js~psr#iterate",
    "class/tariff-psroo/src/index.js~PSR.html#instance-method-iterate",
    "tariff-psroo/src/index.js~PSR#iterate",
    "method"
  ],
  [
    "tariff-psroo/src/index.js~psr#official",
    "class/tariff-psroo/src/index.js~PSR.html#instance-member-official",
    "tariff-psroo/src/index.js~PSR#official",
    "member"
  ],
  [
    "tariff-psroo/src/index.js~psr.parse",
    "class/tariff-psroo/src/index.js~PSR.html#static-method-parse",
    "tariff-psroo/src/index.js~PSR.parse",
    "method"
  ],
  [
    "tariff-psroo/src/index.js~roo",
    "typedef/index.html#static-typedef-ROO",
    "tariff-psroo/src/index.js~ROO",
    "typedef"
  ],
  [
    "tariff-psroo/src/index.js~roocategory",
    "typedef/index.html#static-typedef-ROOCategory",
    "tariff-psroo/src/index.js~ROOCategory",
    "typedef"
  ],
  [
    "tariff-psroo/src/index.js~roooutcome",
    "typedef/index.html#static-typedef-ROOOutcome",
    "tariff-psroo/src/index.js~ROOOutcome",
    "typedef"
  ],
  [
    "tariff-psroo/src/index.js~rooquestion",
    "typedef/index.html#static-typedef-ROOQuestion",
    "tariff-psroo/src/index.js~ROOQuestion",
    "typedef"
  ],
  [
    "tariff-psroo/src/template.js",
    "file/tariff-psroo/src/template.js.html",
    "tariff-psroo/src/template.js",
    "file"
  ]
]